import { Filing } from '../types/api'

export const mockFilings: Filing[] = [
  {
    filing_id: 'F001',
    company_code: '1155',
    company_name: 'Malayan Banking Berhad',
    announcement_date: '2026-01-10',
    document_type: 'Quarterly Report',
    title: 'Q4 2025 Financial Results',
    summary: 'Maybank reported strong Q4 results with net profit increasing 12% YoY to RM2.3 billion, driven by improved net interest margins and lower credit costs.',
    pdf_urls: ['https://example.com/maybank-q4-2025.pdf'],
    sentiment: 'positive',
    tables_count: 15,
    keywords: ['profit', 'NIM', 'credit quality', 'digital banking'],
  },
  {
    filing_id: 'F002',
    company_code: '1155',
    company_name: 'Malayan Banking Berhad',
    announcement_date: '2026-01-05',
    document_type: 'Material Change',
    title: 'Appointment of New Chief Financial Officer',
    summary: 'Maybank announces the appointment of Ms. Sarah Tan as new CFO effective February 1, 2026.',
    pdf_urls: ['https://example.com/maybank-cfo-announcement.pdf'],
    sentiment: 'neutral',
    tables_count: 0,
    keywords: ['appointment', 'CFO', 'management'],
  },
  {
    filing_id: 'F003',
    company_code: '5347',
    company_name: 'Great Eastern Holdings Limited',
    announcement_date: '2026-01-08',
    document_type: 'Annual Report',
    title: 'FY2025 Annual Report',
    summary: 'Great Eastern reports total weighted new sales of $1.2 billion, up 8% from previous year despite challenging market conditions.',
    pdf_urls: ['https://example.com/glico-annual-2025.pdf'],
    sentiment: 'positive',
    tables_count: 24,
    keywords: ['annual report', 'sales growth', 'insurance', 'profitability'],
  },
  {
    filing_id: 'F004',
    company_code: '1082',
    company_name: 'Hong Leong Bank Berhad',
    announcement_date: '2026-01-12',
    document_type: 'Risk Disclosure',
    title: 'Update on Non-Performing Loans Ratio',
    summary: 'HLB discloses NPL ratio increased to 1.8% from 1.5% in previous quarter due to exposure in property development sector.',
    pdf_urls: ['https://example.com/hlbank-npl-update.pdf'],
    sentiment: 'negative',
    tables_count: 5,
    keywords: ['NPL', 'credit risk', 'property', 'provisioning'],
  },
  {
    filing_id: 'F005',
    company_code: '1023',
    company_name: 'CIMB Group Holdings Berhad',
    announcement_date: '2026-01-11',
    document_type: 'Corporate Action',
    title: 'Proposed Acquisition of Digital Payment Platform',
    summary: 'CIMB proposes to acquire 60% stake in FinTech Solutions Sdn Bhd for RM500 million to strengthen digital banking capabilities.',
    pdf_urls: ['https://example.com/cimb-acquisition.pdf'],
    sentiment: 'positive',
    tables_count: 8,
    keywords: ['acquisition', 'digital banking', 'fintech', 'expansion'],
  },
  {
    filing_id: 'F006',
    company_code: '5183',
    company_name: 'Public Bank Berhad',
    announcement_date: '2026-01-09',
    document_type: 'Quarterly Report',
    title: 'Q4 2025 Results Announcement',
    summary: 'Public Bank maintains strong asset quality with gross impaired loans ratio at 0.3%, net profit of RM1.8 billion for the quarter.',
    pdf_urls: ['https://example.com/pbbank-q4-2025.pdf'],
    sentiment: 'positive',
    tables_count: 12,
    keywords: ['profit', 'asset quality', 'lending growth'],
  },
  {
    filing_id: 'F007',
    company_code: '6888',
    company_name: 'Axiata Group Berhad',
    announcement_date: '2026-01-07',
    document_type: 'Material Change',
    title: 'Regulatory Update - Myanmar Operations',
    summary: 'Axiata provides update on regulatory challenges in Myanmar market, potential impairment of RM1.2 billion.',
    pdf_urls: ['https://example.com/axiata-myanmar-update.pdf'],
    sentiment: 'negative',
    tables_count: 3,
    keywords: ['regulatory', 'impairment', 'Myanmar', 'risk'],
  },
  {
    filing_id: 'F008',
    company_code: '5225',
    company_name: 'Petronas Chemicals Group Berhad',
    announcement_date: '2026-01-06',
    document_type: 'Quarterly Report',
    title: 'Q4 2025 Financial Performance',
    summary: 'Petronas Chemicals reports revenue of RM5.2 billion, down 5% YoY due to lower product prices offset by higher sales volume.',
    pdf_urls: ['https://example.com/pchem-q4-2025.pdf'],
    sentiment: 'neutral',
    tables_count: 18,
    keywords: ['revenue', 'product prices', 'volume', 'chemicals'],
  },
  {
    filing_id: 'F009',
    company_code: '4863',
    company_name: 'Tenaga Nasional Berhad',
    announcement_date: '2026-01-13',
    document_type: 'Risk Disclosure',
    title: 'Coal Price Volatility Impact Assessment',
    summary: 'TNB assesses potential impact of coal price increases on operational costs, estimated additional cost of RM800 million for 2026.',
    pdf_urls: ['https://example.com/tnb-coal-assessment.pdf'],
    sentiment: 'negative',
    tables_count: 7,
    keywords: ['coal prices', 'operational costs', 'energy', 'risk'],
  },
  {
    filing_id: 'F010',
    company_code: '7277',
    company_name: 'Genting Malaysia Berhad',
    announcement_date: '2026-01-04',
    document_type: 'Corporate Action',
    title: 'Expansion of Integrated Resort - Phase 3',
    summary: 'Genting Malaysia announces RM2.5 billion investment for Phase 3 expansion including new hotel tower and leisure attractions.',
    pdf_urls: ['https://example.com/genm-expansion.pdf'],
    sentiment: 'positive',
    tables_count: 6,
    keywords: ['expansion', 'capex', 'resort', 'tourism'],
  },
]

export function getFilingsByCompany(companyCode: string): Filing[] {
  return mockFilings.filter(f => f.company_code === companyCode)
}

export function getFiling(filingId: string): Filing | undefined {
  return mockFilings.find(f => f.filing_id === filingId)
}
